- name: Alacritty
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Alacritty pre-requisites
      become: yes
      apt:
        package:
          - cargo
          - cmake
          - libfontconfig1-dev
          - libfreetype6-dev

    - name: Build Alacritty
      command: cargo install --git https://github.com/jwilm/alacritty
      args:
        creates: ~/.cargo/bin/alacritty

    - name: Install Alacritty
      become: yes
      copy:
        src: "{{ lookup('env', 'HOME') }}/.cargo/bin/alacritty"
        dest: /usr/local/bin/alacritty
        mode: 0755
        remote_src: yes

    - name: Make Alacritty a terminal alternative
      become: yes
      alternatives:
        name: x-terminal-emulator
        link: /usr/bin/x-terminal-emulator
        path: /usr/local/bin/alacritty
        priority: 20

    - name: Download Alacritty icon
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/jwilm/alacritty/master/extra/logo/alacritty-term.svg
        dest: /usr/share/icons/Alacritty.svg

    - name: Download Alacritty desktop definition
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/jwilm/alacritty/master/extra/linux/alacritty.desktop
        dest: /usr/share/applications/alacritty.desktop
