- name: Alacritty
  hosts: 127.0.0.1
  connection: local

  tasks:
    ### Pop_OS! already includes Alacritty
    - name: Install Alacritty (Pop!_OS)
      become: yes
      apt:
        package: alacritty
      when: "'Pop!_OS' in hostvars[inventory_hostname].ansible_facts.lsb.description"

    ### Non-Pop_OS! variants need to build Alacritty
    - name: Install Alacritty pre-requisites
      become: yes
      apt:
        package:
          - cargo
          - cmake
          - libfontconfig1-dev
          - libfreetype6-dev
      when: "'Pop!_OS' not in hostvars[inventory_hostname].ansible_facts.lsb.description"

    - name: Build Alacritty
      command: cargo install --git https://github.com/jwilm/alacritty
      args:
        creates: ~/.cargo/bin/alacritty
      when: "'Pop!_OS' not in hostvars[inventory_hostname].ansible_facts.lsb.description"

    - name: Install Alacritty
      become: yes
      copy:
        src: "{{ lookup('env', 'HOME') }}/.cargo/bin/alacritty"
        dest: /usr/local/bin/alacritty
        mode: 0755
        remote_src: yes
      when: "'Pop!_OS' not in hostvars[inventory_hostname].ansible_facts.lsb.description"

    - name: Make Alacritty a terminal alternative
      become: yes
      alternatives:
        name: x-terminal-emulator
        link: /usr/bin/x-terminal-emulator
        path: /usr/local/bin/alacritty
        priority: 20
      when: "'Pop!_OS' not in hostvars[inventory_hostname].ansible_facts.lsb.description"

    - name: Download Alacritty icon
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/jwilm/alacritty/master/extra/logo/alacritty-term.svg
        dest: /usr/share/icons/Alacritty.svg
      when: "'Pop!_OS' not in hostvars[inventory_hostname].ansible_facts.lsb.description"

    - name: Download Alacritty desktop definition
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/jwilm/alacritty/master/extra/linux/alacritty.desktop
        dest: /usr/share/applications/alacritty.desktop
      when: "'Pop!_OS' not in hostvars[inventory_hostname].ansible_facts.lsb.description"
