- name: Core OS packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Enable HTTPS APT support
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - software-properties-common

    - name: Install core packages
      become: yes
      apt:
        package:
          - curl
          - dconf-editor
          - git
          - gnome-tweaks
          - htop
          - jq
          - xclip
