- name: Docker
  hosts: 127.0.0.1
  connection: local

  vars:
    apt_override:
      # snwh doesn't support disco yet, so hold it back to cosmic until it does
      docker_distro: "{{ (ansible_distribution_release == 'disco') | ternary('cosmic', ansible_distribution_release) }}"

  tasks:
    - name: Add Docker APT package key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ apt_override.docker_distro }} stable
        filename: docker
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Docker
      become: yes
      apt:
        package: docker-ce

    - name: Enable Docker for current user
      become: yes
      user:
        name={{ lookup('env', "USER") }}
        groups=docker
        append=yes
