- name: Insync
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Insync APT package key
      become: yes
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: ACCAF35C

    - name: Add Insync APT package repository
      become: yes
      apt_repository:
        repo: deb http://apt.insynchq.com/ubuntu bionic non-free contrib
        filename: insync
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Insync
      become: yes
      apt:
        package:
          - insync
          - insync-nautilus

