- name: NodeJS
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Node Version Manager
      shell: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash"
      args:
        creates: ~/.nvm/install.sh

    - name: Test for installed NodeJS LTS
      shell: bash -ic "nvm ls lts/*" >/dev/null
      register: nvm_ls
      ignore_errors: yes

    - name: Install NodeJS LTS
      command: bash -ic "nvm install lts/*"
      when: nvm_ls.failed

    - name: Use NodeJS LTS by default
      command: bash -ic "nvm use --lts"
      when: nvm_ls.failed
