- name: PowerShell Core
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install PowerShell Core
      become: yes
      command: snap install --classic powershell
      args:
        creates: /snap/bin/pwsh
