- name: Slack
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Slack APT package key
      become: yes
      apt_key:
        url: https://packagecloud.io/slacktechnologies/slack/gpgkey

    - name: Add Slack APT package repository
      become: yes
      apt_repository:
        repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
        filename: slack
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Slack Desktop
      become: yes
      apt:
        package: slack-desktop
