- name: Sublime
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Sublime APT package key
      become: yes
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg

    - name: Add Sublime APT package repository
      become: yes
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        filename: sublime
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Sublime tools
      become: yes
      apt:
        package:
          - sublime-merge
          - sublime-text
