- name: VS Code
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Microsoft APT package key
      become: yes
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add VS Code APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        filename: vscode
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install VS Code
      become: yes
      apt:
        package: code

    - name: Install VS Code Extentions
      become: no
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - formulahendry.dotnet-test-explorer              # .NET Core Test Explorer
        - vscoss.vscode-ansible                           # Ansible
        - ms-azure-devops.azure-pipelines                 # Azure Pipelines
        - ms-vscode.csharp                                # C#
        - streetsidesoftware.code-spell-checker           # Code Spell Checker
        - peterjausovec.vscode-docker                     # Docker
        - editorconfig.editorconfig                       # EditorConfig for VS Code
        - thenikso.github-plus-theme                      # GitHub Plus Theme
        - eamodio.gitlens                                 # GitLens
        - ms-kubernetes-tools.vscode-kubernetes-tools     # Kubernetes
        - ms-vsliveshare.vsliveshare-pack                 # Live Share Extension Pack
        - pkief.material-icon-theme                       # Material Icon Theme
        - ms-vscode.powershell                            # PowerShell
        - wallabyjs.quokka-vscode                         # Quokka.js
        - shan.code-settings-sync                         # Settings Sync
        - eamodio.toggle-excluded-files                   # Toggle Excluded Files
        - ms-vscode.vscode-typescript-tslint-plugin       # TSLint
        - pflannery.vscode-versionlens                    # Version Lens
        - visualstudioexptteam.vscodeintellicode          # Visual Studio IntelliCode
